openapi: 3.0.0

info:
  title: API Sistema Comercial
  version: 1.0.0

servers:
  - url: http://localhost:3000

tags:
  - name: Socios
    description: Gestión de socios

paths:
  /api/socios:
    $ref: '../modules/socios/docs/paths.yml#/socio'
  /api/socios/{id}:
    $ref: '../modules/socios/docs/paths.yml#/socio-id'
  /api/socios/select:
    $ref: '../modules/socios/docs/paths.yml#/socio-select'
  /api/socios/deleteds:
    $ref: '../modules/socios/docs/paths.yml#/socio-deleteds'
  /api/socios/restore/{id}:
    $ref: '../modules/socios/docs/paths.yml#/socio-restore'
  /api/socios/toggle-status/{id}:
    $ref: '../modules/socios/docs/paths.yml#/socio-toggle-status'
