services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '2002'
      POSTGRES_DB: bd_otb
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build:
      context: .
      target: development
    container_name: server_otb_dev
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - node_modules_otb_backend:/app/node_modules
      - ./uploads:/app/uploads
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=2002
      - DB_NAME=bd_otb
      - PORT=3000
      - NODE_ENV=development
      - JWT_SECRET=tu_secreto_aqui
      - JWT_EXPIRES_IN=720h
      - BANCO_ECONOMICO_BASE_URL=https://apimktdesa.baneco.com.bo/ApiGateway
      - BANCO_ECONOMICO_USER=26551010
      - BANCO_ECONOMICO_PASSWORD=1234
      - BANCO_ECONOMICO_AES_KEY=40A318B299F245C2B697176723088629
      - BANCO_ECONOMICO_ACCOUNT=1061602532
    depends_on:
      - postgres
volumes:
  postgres_data:
  node_modules_otb_backend:
