services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '2002'
      POSTGRES_DB: bd_otb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build:
      context: .
      target: development
    container_name: server_otb_dev
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - ./.env
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    depends_on:
      - postgres
volumes:
  postgres_data:
